### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Anikeshpatel** [mukeshsolanki/photofilter#11]
### Subject of the issue
Behave like sucks
Too slow
No Documentation

### Your environment
* version of angular-translate
* version of angular
* which browser and its version

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

### Expected behavior
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by mukeshsolanki** [comment]
What is the issue you are facing also which image are you using and what version of the library did you try? @Anikeshpatel
