### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by tobilvr** [mukeshsolanki/photofilter#3]
While trying to compiling to project this error comes out.
Error:Host name 'repo.commonsware.com.s3.amazonaws.com' does not match the certificate subject provided by the peer (CN=*.s3.amazonaws.com, O=Amazon.com Inc., L=Seattle, ST=Washington, C=US)

Any solutions please?
Thanks alot for your awesome work and anticipated support :)

**Comment by mukeshsolanki** [comment]
This does not seem to related to the library as no network activity takes place. Maybe if you could share the code i could have a look at it

**Comment by tobilvr** [comment]
Thanks for the reply, you are right, it is not related to the library....so sorry for that,.....solved it by rebuilding gradle. Thanks so much for everything, 👍
