### ISSUE TITLE
unable to import photofilter to my project via gradle

### ISSUE THREAD

**Issue by TharakaDamayantha** [mukeshsolanki/photofilter#4]
First I must thank you for your awesome project.
 I followed following two steps as you mentioned.
![image](https://cloud.githubusercontent.com/assets/25580730/24459076/4c98c022-14b8-11e7-9d12-caeb1f44aa64.png)
but android studio gives me following error  
![image](https://cloud.githubusercontent.com/assets/25580730/24459174/84ab9fa2-14b8-11e7-8464-2891169cd457.png)

how can i avoid this error and import your project via gradle ? or let me know if there a another error free way that i can import your library. many thanks

**Comment by TranBaVinhSon** [comment]
I have a same problem

**Comment by mukeshsolanki** [comment]
That's strange it seems to be working fine can you try again

**Comment by TharakaDamayantha** [comment]
ahh thanks for the reply and no i was not able to  get it work.  May be issue a with newer versions of updated android studio? anyway i will try at another time and will let you know. thnks

**Comment by mukeshsolanki** [comment]
Hey can you check this once again and see if your able to make it work if so then can we close this issue??

**Comment by mukeshsolanki** [comment]
closing no response
