### ISSUE TITLE
what is this error?

### ISSUE THREAD

**Issue by miladlimiless** [mukeshsolanki/photofilter#5]
## Description ##
Thank you very much for building this library.
I'm doing all the steps correctly, but is this error happening?

## error ##
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.mukeshsolanki:photofilter:<latest-version>.

Could not resolve com.github.mukeshsolanki:photofilter:<latest-version>.
Required by:
    project :app
 > Could not resolve com.github.mukeshsolanki:photofilter:<latest-version>.
    > Could not get resource 'https://jcenter.bintray.com/com/github/mukeshsolanki/photofilter/%3Clatest-version%3E/photofilter-%3Clatest-version%3E.pom'.
          > Could not GET 'https://jcenter.bintray.com/com/github/mukeshsolanki/photofilter/%3Clatest-version%3E/photofilter-%3Clatest-version%3E.pom'.
                   > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/159.122.18.156] failed: Connection timed out: connect
                               > Connection timed out: connect

**Comment by mukeshsolanki** [comment]
Make sure you added 
```
allprojects {
  repositories {
    ...
    maven { url "https://jitpack.io" }
  }
}
``` 
in the `build.gradel` in the root dir and 
```
dependencies {
        implementation 'com.github.mukeshsolanki:photofilter:1.0.3'
}
```
in the `build.gradel` under app module

**Comment by miladlimiless** [comment]
## Error resolved ##
Thank you very much for your guide
